import { useState } from 'react';
import type { ReactNode } from 'react';
import type { Action } from '../shared/protocol';
import { RECIPES, SHELTERS, UPGRADE_RULES, WEAPONS, itemIds, type Inventory, type ItemId, type SurvivalPublicWorld } from '../shared/survival';
import { CharacterPortrait } from './CharacterPortrait';
import { SurvivalMap } from './SurvivalMap';
import { ShelterDuties } from './ShelterDuties';
import { ShelterIllustration, type SurvivalScreenProps } from './SurvivalLobby';
import './survival-ui.css';

type Tab = 'duties' | 'inventory' | 'craft' | 'crew' | 'shelter' | 'goals';
const tabs: { id: Tab; title: string; icon: string }[] = [{ id: 'inventory', title: 'Inventory', icon: 'backpack' }, { id: 'craft', title: 'Craft', icon: 'workbench' }, { id: 'crew', title: 'Crew', icon: 'crew' }, { id: 'shelter', title: 'Shelter', icon: 'shelter' }, { id: 'goals', title: 'Goals', icon: 'goals' }, { id: 'duties', title: 'Duties', icon: 'crew' }];
const names: Record<string, string> = { wood: 'Wood', metal: 'Metal', cloth: 'Cloth', electronics: 'Electronics', ammo: 'Ammunition', food: 'Food', water: 'Water', medicine: 'Medicine', armor: 'Body armor', backpack: 'Backpack', boots: 'Boots', workbench: 'Workbench', storage: 'Storage', barricade: 'Barricade', rain_collector: 'Rain collector' };
const roleDescriptions = { guardian: 'Fights infected and protects the shelter.', medic: 'Heals nearby players.', scavenger: 'Brings supplies back to base.', engineer: 'Repairs and reinforces your shelter.' };
const clamp = (number: number) => Math.max(0, Math.min(100, number));
const duration = (ms: number) => { const seconds = Math.max(0, Math.ceil(ms / 1000)); return seconds >= 60 ? `${Math.floor(seconds / 60)}m ${seconds % 60}s` : `${seconds}s`; };

export function SurvivalItemIcon({ name, className = '' }: { name: string; className?: string }) {
  const drawing: Record<string, ReactNode> = {
    wood: <><path d="M9 30 25 10 44 23 28 43Z" fill="#826448" /><path d="m25 10 6 10-3 23M9 30 22 32 44 23" /><path d="m17 27 12-9M24 33l10-9" /></>,
    metal: <><path d="m8 27 29-13 10 10-29 14Z" fill="#798e92" /><path d="m8 27 10 11v7L8 35Zm10 11 29-14v7L18 45Z" fill="#3b535e" /><path d="m14 27 24-9" /></>,
    cloth: <><path d="M10 18Q16 8 27 13L43 19 34 43Q19 37 9 44L16 27Z" fill="#9d9b81" /><path d="m16 27 17 6M20 15l9 21M12 38l19 3" strokeDasharray="2 3" /></>,
    electronics: <><rect x="11" y="11" width="31" height="32" rx="3" fill="#416d65" /><rect x="20" y="19" width="14" height="14" rx="2" fill="#203d42" /><path d="M22 13v6m6-6v6m6-6v6M22 33v7m6-7v7m6-7v7M14 22h6m-6 6h6m14-6h5m-5 6h5" /></>,
    ammo: <>{[13, 26, 39].map(x => <g key={x}><path d={`M${x-4} 22q4-13 8 0v18h-8Z`} fill="#c7a266" /><path d={`M${x-5} 40h10M${x-4} 24h8`} /></g>)}</>,
    food: <><rect x="14" y="14" width="28" height="31" rx="3" fill="#907b59" /><ellipse cx="28" cy="14" rx="14" ry="5" fill="#b2a285" /><path d="M15 23h26v14H15" fill="#52695b" /><path d="M25 27v7m6-7v7M22 30h12" /></>,
    water: <><path d="M21 9h13v8l6 7v18q-12 9-25 0V24l6-7Z" fill="#476e85" /><rect x="20" y="8" width="15" height="6" rx="1" fill="#a3bec4" /><path d="M20 26h15v13H20" fill="#70a7b6" /><path d="M25 20v4M21 43h14" /></>,
    medicine: <><rect x="10" y="15" width="37" height="28" rx="5" fill="#785c53" /><path d="M21 15v-4h14v4" /><path d="M25 22h7v5h5v7h-5v5h-7v-5h-5v-7h5Z" fill="#e3c1aa" stroke="none" /></>,
    pistol: <><path d="M9 16h37v12H30l-5 17H14l5-17H9Z" fill="#789099" /><path d="M10 21h29m-18 8h8M18 36h8" /><path d="M35 28v6H27" /></>,
    rifle: <><path d="M8 23h9v-6h25v6h10v5H29l-8 6-7 11-6-3 8-15H8Z" fill="#798d90" /><path d="M19 29h12v13H20Z" fill="#475d64" /><path d="M21 15h15M24 12v5m8-5v5" /><path d="m10 27 8 6" /></>,
    shotgun: <><path d="M7 23h38v8H23L12 43 6 38l12-15" fill="#8e7454" /><path d="M22 21h28v5H22Z" fill="#778c90" /><path d="M27 28h16v6H27Z" fill="#526871" /><path d="M13 32 8 38" /></>,
    armor: <><path d="M15 10 24 16h7l9-6 7 12-6 7v17H13V29l-6-7Z" fill="#526e69" /><path d="M20 20h15v18H20Z" fill="#314a50" /><path d="M16 29h4m15 0h5M20 24h15m-15 10h15" /></>,
    backpack: <><rect x="13" y="13" width="30" height="32" rx="8" fill="#837856" /><path d="M20 14v-4h15v4M13 25H9v14h4m30-14h4v14h-4" /><rect x="19" y="30" width="18" height="11" rx="3" fill="#5c644c" /><path d="M21 21h14M24 30v5m8-5v5" /></>,
    boots: <><path d="M15 10h14v21l15 5v9H14V27Z" fill="#81735a" /><path d="M16 18h12m-12 6h12M15 40h29M29 32l-4 6" /></>,
    workbench: <><path d="M8 25h41v7H8Zm6 7v15m29-15v15M14 41h29" fill="#94734f" /><path d="M15 24V13h12v11M34 23l9-11m-4-4 8 8" /></>,
    storage: <><path d="M10 13h37v34H10Z" fill="#745f46" /><path d="m10 13 37 34M10 47 47 13M10 22h37m-37 17h37" /><path d="M22 27h14v7H22Z" fill="#b29562" /></>,
    barricade: <><path d="M11 9h7v40h-7Zm17 0h7v40h-7Zm17 0h7v40h-7Z" fill="#94784f" /><path d="M8 20h46v7H8Zm0 17h46v7H8Z" fill="#6f604c" /></>,
    rain_collector: <><path d="M11 20h37l-5 28H16Z" fill="#506c74" /><ellipse cx="29" cy="20" rx="19" ry="6" fill="#86afb5" /><path d="M29 5q-7 8 0 11 7-3 0-11Z" fill="#8ed2da" /><path d="M21 31h15m-16 6h17" /></>,
    crew: <><circle cx="27" cy="17" r="8" fill="#be976f" /><path d="M12 44q0-18 15-18t15 18" fill="#577275" /><path d="M10 22a6 6 0 1 1 0-11m-4 27q0-12 10-14m27-2a6 6 0 1 0 0-11m4 27q0-12-10-14" /></>,
    shelter: <><path d="m6 26 23-19 23 19M13 23v24h32V23" fill="#687861" /><path d="M24 47V31h11v16" fill="#2b4546" /><path d="M17 28h5v6h-5m20-6h5v6h-5" /></>,
    goals: <><rect x="13" y="12" width="30" height="37" rx="3" fill="#627d70" /><path d="M21 9h14v8H21Z" fill="#9db095" /><path d="m19 25 3 3 5-6m4 4h7m-19 10 3 3 5-6m4 4h7" /></>,
  };
  return <svg className={`survival-item-icon ${className}`} width="56" height="56" viewBox="0 0 56 56" fill="none" stroke="#bfd0bd" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{drawing[name] ?? drawing.electronics}</svg>;
}

function Cost({ cost, inventory, label = 'Materials required' }: { cost: Partial<Inventory>; inventory: Inventory | undefined; label?: string }) {
  return <div className="survival-cost" aria-label={label}>{Object.entries(cost).map(([item, amount]) => <span key={item} className={inventory && inventory[item as ItemId] < amount ? 'is-missing' : ''}><SurvivalItemIcon name={item} /><b>{amount}</b> {names[item]}</span>)}</div>;
}

function Meter({ title, value, max = 100, tone = '' }: { title: string; value: number; max?: number; tone?: string }) {
  return <div className={`survival-meter ${tone}`}><span>{title}<b>{Math.ceil(value)}{max !== 100 && ` / ${max}`}</b></span><div role="progressbar" aria-label={title} aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={max}><i style={{ width: `${clamp(value / max * 100)}%` }} /></div></div>;
}

function Jobs({ world }: { world: SurvivalPublicWorld }) {
  if (!world.jobs.length) return null;
  return <section className="survival-jobs" aria-label="Upgrade jobs"><span className="survival-kicker">WORK IN PROGRESS · {world.jobs.length} / 3</span><div>{world.jobs.map(job => <div className="survival-job" key={job.id}><span className="survival-job-spinner" /><strong>{job.label}</strong><time>{duration(job.finishAt - world.elapsedMs)}</time></div>)}</div></section>;
}

export function SurvivalGame({ view, send, online, pending, speakingId }: SurvivalScreenProps) {
  const [tab, setTab] = useState<Tab>('inventory');
  const world = view.survival;
  const me = view.survivorMe ?? null;
  if (!world) return <section className="survival-panel">Connecting to your survival world…</section>;
  const isHost = view.hostId === view.selfId;
  const player = world.players.find(subject => subject.id === view.selfId);
  const nearBase = !!player && Math.hypot(player.x - world.shelter.x, player.y - world.shelter.y) <= 200;
  const playable = online && world.active && !world.paused && !!me && me.hp > 0;
  const jobReady = playable && nearBase && world.jobs.length < 3;
  const equipment = me?.weapons.find(weapon => weapon.id === me.equippedWeapon);
  const carrying = me ? itemIds.reduce((total, item) => total + (item === 'ammo' ? 0 : me.inventory[item]), 0) : 0;
  const capacity = 60 + (me?.gear.find(gear => gear.id === 'backpack')?.level ?? 0) * 20 + (world.facilities.find(facility => facility.kind === 'storage')?.level ?? 0) * 20;
  const hour = Math.floor(world.hour);
  const minute = Math.floor((world.hour - hour) * 60);
  const dutiesRemaining = world.community?.duties.filter(duty => duty.day === world.day && duty.memberId === view.selfId && !duty.completed).length ?? 0;
  const goalsReady = world.goals.filter(goal => !goal.claimed && goal.progress >= goal.target).length;
  const action = (command: Action) => send(command);
  const upgrade = (kind: 'weapon' | 'gear' | 'survivor' | 'facility' | 'shelter', targetId: string) => action({ type: 'survival_upgrade', kind, targetId });
  const upgradeControl = (kind: keyof typeof UPGRADE_RULES, targetId: string, level: number, name: string) => {
    if (level >= 5) return <span className="survival-chip">MAXIMUM LEVEL</span>;
    const rule = UPGRADE_RULES[kind];
    const cost = Object.fromEntries(Object.entries(rule.cost).map(([item, amount]) => [item, amount * (level + 1)])) as Partial<Inventory>;
    const canAfford = !!me && Object.entries(cost).every(([item, amount]) => me.inventory[item as ItemId] >= amount);
    const inProgress = world.jobs.some(job => job.kind === kind && job.targetId === (kind === 'shelter' ? 'shelter' : targetId) && (kind !== 'weapon' && kind !== 'gear' || job.ownerId === view.selfId));
    const speed = 1 + .2 * (world.facilities.find(facility => facility.kind === 'workbench')?.level ?? 0);
    return <div className="survival-upgrade-control"><Cost cost={cost} inventory={me?.inventory} /><div><time>LV {level + 1} · {duration(rule.durationMs * (level + 1) / speed)}</time><button aria-label={`Upgrade ${name}`} className="survival-button secondary small" disabled={!jobReady || !canAfford || inProgress || pending.includes('survival_upgrade')} onClick={() => upgrade(kind, targetId)}>{inProgress ? 'Upgrading…' : `Upgrade ${kind}`}</button></div></div>;
  };
  return <div className="survival-ui survival-game" data-testid="survival-game">
    <div className="survival-world-title"><div><span className="survival-kicker"><span className="survival-beacon" /> {world.night ? 'NIGHT WATCH' : 'QUARANTINE ZONE'}</span><h1>Survive the Experiment.</h1></div><div className="survival-time" data-testid="day-counter"><span>{world.night ? '☾' : '☀'} <b>DAY {world.day}</b></span><strong>{String(hour).padStart(2, '0')}:{String(minute).padStart(2, '0')}</strong><small>WEEK {world.week} · MONTH {world.month}</small>{isHost && <button className="survival-button secondary small" disabled={!online || !world.active || pending.includes('survival_pause')} onClick={() => action({ type: 'survival_pause', paused: !world.paused })}>{world.paused ? 'Resume expedition' : 'Pause expedition'}</button>}</div></div>
    {world.paused && <div className="survival-notice" role="status"><strong>World paused.</strong> Movement, attacks, needs, and upgrade timers are held.</div>}
    {!world.active && <div className="survival-notice" role="status"><strong>The shelter has fallen.</strong> Your crew’s survival record is saved. {isHost && <button className="survival-button primary small" disabled={!online || pending.includes('rematch')} onClick={() => action({ type: 'rematch' })}>Return to lobby</button>}</div>}
    {!me && <div className="survival-notice" role="status">Observer mode · Follow the crew. Personal supplies and equipment remain private.</div>}
    {me && <div className="survival-player-hud"><div className="survival-condition"><Meter title="Health" value={me.hp} tone={me.hp <= 30 ? 'danger' : ''} /><Meter title="Food" value={me.hunger} tone="amber" /><Meter title="Water" value={me.thirst} tone="blue" /></div><div className="survival-weapon-hud"><SurvivalItemIcon name={me.equippedWeapon} /><div><strong>{WEAPONS[me.equippedWeapon].name} <span>LV {equipment?.level ?? 1}</span></strong><span>{equipment?.magazine ?? 0} / {me.inventory.ammo} <small>mag / reserve</small></span></div><button className="survival-button secondary small" disabled={!playable || me.reloadRemainingMs > 0 || me.inventory.ammo <= 0} onClick={() => action({ type: 'survival_reload' })}>{me.reloadRemainingMs > 0 ? `Reload ${duration(me.reloadRemainingMs)}` : 'Reload'}</button></div></div>}
    <div className={`survival-wave-strip ${world.wave.active ? 'is-attacking' : ''}`}><span className="survival-wave-icon" aria-hidden="true">{world.wave.active ? '⚠' : '◈'}</span><div><strong>{world.wave.active ? `HORDE WAVE ${world.wave.number}` : 'PREPARE FOR THE NEXT HORDE'}</strong><span>{world.wave.active ? `${world.enemies.filter(enemy => enemy.horde).length + world.wave.remainingSpawns} infected remain. Defend your shelter.` : `Next horde in ${duration(world.wave.nextAt - world.elapsedMs)}. Scavenge and prepare.`}</span></div><div><span>BASE INTEGRITY</span><b>{Math.ceil(world.shelter.hp)} / {world.shelter.maxHp}</b><div className="survival-tiny-bar"><i style={{ width: `${clamp(world.shelter.hp / world.shelter.maxHp * 100)}%` }} /></div></div></div>
    <SurvivalMap world={world} me={me} selfId={view.selfId} members={view.members} send={send} online={online} />
    {me && me.hp <= 0 && <div className="survival-notice downed" role="status"><div><strong>You are down. Shelter recovery is on its way.</strong><p>{me.respawnRemainingMs > 0 ? `Recovery at shelter available in ${duration(me.respawnRemainingMs)}.` : 'Recover at your shelter to rejoin the defense.'}</p></div><button className="survival-button primary" disabled={!online || world.paused || me.respawnRemainingMs > 0 || !world.active} onClick={() => action({ type: 'survival_respawn' })}>Recover at shelter</button></div>}
    <nav className="survival-tool-nav" aria-label="Survival tools">{tabs.map(item => <button key={item.id} aria-label={item.title} aria-pressed={tab === item.id} className={tab === item.id ? 'is-selected' : ''} onClick={() => setTab(item.id)}><SurvivalItemIcon name={item.icon} /><span>{item.title}</span>{item.id === 'goals' && goalsReady > 0 && <b>{goalsReady}</b>}{item.id === 'duties' && dutiesRemaining > 0 && <b>{dutiesRemaining}</b>}</button>)}</nav>
    <section className="survival-panel survival-tools-panel" aria-label={tabs.find(item => item.id === tab)?.title}>
      {tab === 'inventory' && <><div className="survival-panel-title"><div><span className="survival-kicker">YOUR SUPPLIES / PRIVATE</span><h2>Carry what keeps you alive.</h2></div><span className="survival-chip">{me ? `PACK ${carrying} / ${capacity}` : 'OBSERVER'}</span></div>{me ? <><div className="survival-inventory-grid">{itemIds.map(item => <div className={`survival-inventory-item ${me.inventory[item] === 0 ? 'empty' : ''}`} key={item}><SurvivalItemIcon name={item} /><strong>{me.inventory[item]}</strong><span>{names[item]}</span>{(['food', 'water', 'medicine'] as string[]).includes(item) && <button disabled={!playable || me.inventory[item] <= 0 || pending.includes('survival_consume')} onClick={() => action({ type: 'survival_consume', item: item as 'food' | 'water' | 'medicine' })}>{item === 'food' ? 'Eat' : item === 'water' ? 'Drink' : 'Heal'}</button>}</div>)}</div><div className="survival-subheading"><h3>Weapons & gear</h3><span className="survival-muted">Upgrades require supplies and a trip to your shelter.</span></div><div className="survival-equipment-grid">{me.weapons.map(weapon => <article className="survival-equipment-card" key={weapon.id}><SurvivalItemIcon name={weapon.id} /><div><h3>{WEAPONS[weapon.id].name}<span>LV {weapon.level}</span></h3><p>{Math.round(WEAPONS[weapon.id].damage * (1 + (weapon.level - 1) * .2))} base damage · {WEAPONS[weapon.id].range} range</p><div className="survival-button-row"><button className="survival-button secondary small" disabled={!playable || me.equippedWeapon === weapon.id} onClick={() => action({ type: 'survival_equip', kind: 'weapon', targetId: weapon.id })}>{me.equippedWeapon === weapon.id ? 'Equipped' : 'Equip'}</button></div>{upgradeControl('weapon', weapon.id, weapon.level, WEAPONS[weapon.id].name)}</div></article>)}{me.gear.map(gear => <article className="survival-equipment-card" key={gear.id}><SurvivalItemIcon name={gear.id} /><div><h3>{names[gear.id]}<span>LV {gear.level}</span></h3><p>{gear.id === 'armor' ? 'Protection from infected attacks' : gear.id === 'boots' ? 'Move faster through the zone' : 'Carry more supplies'}</p><div className="survival-button-row"><span className="survival-chip">EQUIPPED / PASSIVE</span></div>{upgradeControl('gear', gear.id, gear.level, names[gear.id])}</div></article>)}</div>{me.gear.length === 0 && <p className="survival-muted">Find gear in containers or craft your first armor, backpack, and boots.</p>}</> : <p className="survival-muted">Inventory belongs to each player. Join a CPU seat to control a survivor.</p>}</>}
      {tab === 'craft' && <><div className="survival-panel-title"><div><span className="survival-kicker">TURN SCRAP INTO A SECOND CHANCE</span><h2>Craft & build.</h2></div><span className="survival-chip">{world.jobs.length} / 3 JOBS</span></div><p className="survival-muted">{nearBase ? 'You are at your shelter. Materials are paid when a job starts.' : 'Return to your shelter to start crafting or upgrades.'} Jobs finish while the world is active.</p><div className="survival-craft-grid">{RECIPES.map(recipe => { const canAfford = !!me && Object.entries(recipe.cost).every(([item, amount]) => me.inventory[item as ItemId] >= amount); const craftInProgress = world.jobs.some(job => job.kind === 'craft' && job.targetId === recipe.id && (recipe.facility || ((recipe.weapon || recipe.gear) && job.ownerId === view.selfId))); const alreadyOwned = !!(recipe.weapon && me?.weapons.some(weapon => weapon.id === recipe.weapon)) || !!(recipe.gear && me?.gear.some(gear => gear.id === recipe.gear)) || !!(recipe.facility && world.facilities.some(facility => facility.kind === recipe.facility)); return <article className="survival-recipe" key={recipe.id}><div className="survival-recipe-heading"><SurvivalItemIcon name={recipe.weapon ?? recipe.gear ?? recipe.facility ?? recipe.output?.item ?? (recipe.repairShelterHp ? 'shelter' : recipe.id)} /><div><h3>{recipe.name}</h3><p>{recipe.description}</p></div></div><Cost cost={recipe.cost} inventory={me?.inventory} /><div className="survival-recipe-footer"><time>{duration(recipe.durationMs / (1 + .2 * (world.facilities.find(facility => facility.kind === 'workbench')?.level ?? 0)))}</time><button aria-label={`${recipe.facility ? 'Build' : 'Craft'} ${recipe.name}`} className="survival-button secondary small" disabled={!jobReady || !canAfford || alreadyOwned || craftInProgress || (!!recipe.repairShelterHp && world.shelter.hp >= world.shelter.maxHp) || pending.includes('survival_craft')} onClick={() => action({ type: 'survival_craft', recipeId: recipe.id })}>{alreadyOwned ? 'Owned' : craftInProgress ? 'Building…' : recipe.repairShelterHp ? 'Repair' : recipe.facility ? 'Build' : 'Craft'}</button></div></article>; })}</div></>}
      {tab === 'duties' && <ShelterDuties view={view} send={send} online={online} pending={pending} />}
      {tab === 'crew' && <><div className="survival-panel-title"><div><span className="survival-kicker">NO ONE SURVIVES ALONE</span><h2>Your community.</h2></div><span className="survival-chip">{world.survivors.length} / {world.shelter.capacity} SURVIVORS</span></div><p className="survival-muted">Search the zone for survivors and approach their rescue markers. A rescue costs 2 food + 1 medicine. Recruits fight, heal, gather, or repair according to their role.</p>{world.survivors.length > 0 ? <div className="survival-crew-grid">{world.survivors.map(survivor => <article className="survival-survivor-card" key={survivor.id}><CharacterPortrait seed={survivor.id} speaking={speakingId === survivor.id} mood={survivor.hp < 35 ? 'critical' : 'calm'} /><div><span className="survival-kicker">{survivor.role} · LEVEL {survivor.level}</span><h3>{survivor.name}</h3><p>{roleDescriptions[survivor.role]}</p><Meter title="Health" value={survivor.hp} />{upgradeControl('survivor', survivor.id, survivor.level, survivor.name)}</div></article>)}</div> : <div className="survival-empty"><SurvivalItemIcon name="crew" /><strong>Your shelter is waiting for its first survivor.</strong><p>Scout the rescue markers on the map. Stay close and interact to bring them home.</p></div>}</>}
      {tab === 'shelter' && <><div className="survival-panel-title"><div><span className="survival-kicker">YOUR SINGLE ACTIVE SHELTER</span><h2>{SHELTERS[world.shelter.type].name} <span className="survival-heading-level">LEVEL {world.shelter.level}</span></h2></div><span className="survival-chip">{world.shelter.defense} DEFENSE</span></div><div className="survival-base-overview"><ShelterIllustration type={world.shelter.type} /><div><p>{SHELTERS[world.shelter.type].description}</p><Meter title="Shelter health" value={world.shelter.hp} max={world.shelter.maxHp} /><p className="survival-muted">Capacity {world.shelter.capacity} survivors · {world.facilities.length} facilities built</p>{upgradeControl('shelter', world.shelter.siteId, world.shelter.level, SHELTERS[world.shelter.type].name)}</div></div><div className="survival-subheading"><h3>Facilities</h3><button className="survival-text-button" onClick={() => setTab('craft')}>Build a facility ↗</button></div>{world.facilities.length ? <div className="survival-equipment-grid">{world.facilities.map(facility => <article className="survival-equipment-card" key={facility.id}><SurvivalItemIcon name={facility.kind} /><div><h3>{names[facility.kind]}<span>LV {facility.level}</span></h3>{upgradeControl('facility', facility.id, facility.level, names[facility.kind])}</div></article>)}</div> : <p className="survival-muted">Build a workbench, storage, barricade, or rain collector in the Craft panel.</p>}<div className="survival-subheading"><h3>Discovered shelters</h3><span className="survival-muted">Moving replaces your current base.</span></div><div className="survival-site-grid">{world.sites.filter(site => site.discovered).map(site => <article className="survival-site-card" key={site.id}><ShelterIllustration type={site.type} /><div><h3>{SHELTERS[site.type].name}</h3><p>{site.id === world.shelter.siteId ? 'Your current shelter' : `${SHELTERS[site.type].health} durability · ${SHELTERS[site.type].defense} defense`}</p><button className="survival-button secondary small" disabled={!isHost || !playable || site.id === world.shelter.siteId || world.wave.active || !player || Math.hypot(player.x - site.x, player.y - site.y) > 120 || pending.includes('survival_shelter')} onClick={() => action({ type: 'survival_shelter', siteId: site.id })}>{site.id === world.shelter.siteId ? 'Current home' : 'Move shelter here'}</button></div></article>)}</div><p className="survival-muted">The host must reach the new site to move. Moving is blocked during hordes. Levels and facilities carry over; damage carries over proportionally.</p></>}
      {tab === 'goals' && <><div className="survival-panel-title"><div><span className="survival-kicker">SMALL WINS. A LONGER FUTURE.</span><h2>Survival calendar.</h2></div><span className="survival-chip">DAY {world.day}</span></div><p className="survival-muted">Daily goals reset each day; weekly goals each seven days; monthly goals each thirty days. Each shared goal can be claimed once. Its supplies go to the player who claims it.</p>{(['daily', 'weekly', 'monthly'] as const).map(period => <section className="survival-goal-period" key={period}><h3>{period} goals <span>{period === 'daily' ? `Day ${world.day}` : period === 'weekly' ? `Week ${world.week}` : `Month ${world.month}`}</span></h3><div className="survival-goal-grid">{world.goals.filter(goal => goal.period === period).map(goal => <article className={`survival-goal ${goal.claimed ? 'is-claimed' : ''}`} key={goal.id}><div><h4>{goal.title}</h4><span className="survival-muted">Expires after day {goal.expiresDay - 1}</span></div><Meter title="Progress" value={Math.min(goal.progress, goal.target)} max={goal.target} /><Cost cost={goal.reward} inventory={undefined} label="Reward supplies" /><button className="survival-button secondary small" disabled={!playable || goal.claimed || goal.progress < goal.target || pending.includes('survival_claim')} onClick={() => action({ type: 'survival_claim', goalId: goal.id })}>{goal.claimed ? 'Reward collected' : goal.progress >= goal.target ? 'Claim reward' : 'In progress'}</button></article>)}</div></section>)}</>}
      <Jobs world={world} />
      {me && ['craft', 'crew', 'shelter'].includes(tab) && <div className="survival-work-status">{nearBase ? '◈ At shelter' : '↗ Return to shelter'}<span>{world.jobs.length >= 3 ? 'The three job slots are full.' : 'Upgrades use your own collected materials.'}</span></div>}
    </section>
    {world.events.length > 0 && <section className="survival-event-log" aria-label="World events"><span className="survival-kicker">FIELD JOURNAL</span>{world.events.slice(-4).reverse().map(event => <p key={event.id}><span aria-hidden="true">·</span>{event.text}</p>)}</section>}
    <div className="survival-host-tools"><span>World saves automatically. Time stops when all players disconnect.</span></div>
  </div>;
}
